PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gy: <http://grid-observatory.org/ns/2014/GO3#>
 
SELECT DISTINCT ?valErt1 ?dateErt1 ?dateErt2 
{
	?item 	rdf:first ?ert1 ;
			rdf:rest/rdf:first ?ert2 .
	?ert1 	gy:time ?dateErt1 ;
			gy:value ?valErt1.
	?ert2 	gy:time ?dateErt2 .   
}
ORDER BY ?valErt1

