PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gy: <http://grid-observatory.org/ns/2014/GO3#>
 
SELECT ?dateErt1 ?dateErt2 ?valErt1
{
	?ertItem rdf:first ?dateErt1 ;
			gy:value ?valErt1 ;
			rdf:rest/rdf:first ?dateErt2 ;
			rdf:rest/gy:value ?valErt2 .       
}
