PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gy: <http://grid-observatory.org/ns/2014/GO3#>
 
SELECT ?queueName ?dateErt1 ?dateErt2  ?valErt1
{
	  ?iriQueue  rdf:type gy:BDIIEntry ;
	 gy:GlueCEUniqueID ?queueName ;
	 gy:GlueCEStateEstimatedResponseTimeList/rdf:rest*  ?itemCollection .

	?itemCollection rdf:first[
								gy:time ?dateErt1;
								gy:value ?valErt1
							] ;
					rdf:rest/rdf:first/gy:time ?dateErt2.
}
ORDER BY ?valErt1

