PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX gy: <http://grid-observatory.org/ns/2014/GO3#>

SELECT ?queueName ?dateErt1 ?dateErt2  ?valErt1
{
	  ?iriQueue  rdf:type gy:BDIIEntry ;
	 gy:GlueCEUniqueID ?queueName ;
	 gy:GlueCEStateEstimatedResponseTimeList/rdf:rest*  ?itemCollection .

	?itemCollection rdf:first[
								gy:time ?dateErt1;
								gy:value ?valErt1
							] ;
					rdf:rest/rdf:first/gy:time ?dateErt2.

    FILTER ( ?dateErt1>= xsd:dateTime("2005-01-01T00:00:00Z") && ?dateErt2<= xsd:dateTime("2005-01-02T00:00:00Z") )				  
} order by ?dateErt1
